In [1]:
import numpy as np
np.set_printoptions(suppress=True)

from shutil import copyfile
import random
from importlib import reload


from keras.utils import plot_model

from game import Game, GameState
from agent import Agent
from memory import Memory
from model import Densely_connected_net
# from model import Residual_CNN
from funcs import playMatches, playMatchesBetweenVersions

import loggers as lg


from settings import run_folder, run_archive_folder
import initialise
import pickle

from model import Densely_connected_net
import config

print(config.LEARNING_RATE, config.TRAINING_LOOPS)

/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
def softmax_normalize(x):
    b = x.max()
    y = np.exp(x - b)
    return y / y.sum()

def replay(ltmemory):
    model.printWeightAverages()
    minibatch = random.sample(ltmemory, len(ltmemory))

    training_states = np.array(
        [model.convertToModelInput(row['state']) for row in minibatch])
    training_targets = {'value_head': np.array(
        [row['value'] for row in minibatch]), 'policy_head': np.array([row['AV'] for row in minibatch])}
    print(training_states, training_targets)
    fit = model.fit(training_states, training_targets,
                         epochs=config.TRAINING_LOOPS, verbose=1, validation_split=0, batch_size=32)
    model.printWeightAverages()
    print('NEW LOSS %s', fit.history)
    
    y = model.predict(training_states)
    vh = y[0]
    ph = y[1]
    for i in range(30):
        print(training_states[i])
        print(vh[i], training_targets['value_head'][i])
        print(softmax_normalize(ph[i]), training_targets['policy_head'][i])
        
mem = pickle.load(open("run/memory/memory0007.p", "rb"))
ltmemory = mem.ltmemory
env = Game()                  
model = Densely_connected_net(
    config.REG_CONST, config.LEARNING_RATE, env.input_shape,   env.action_size)
# model.viewLayers()
                  
replay(ltmemory)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

Epoch 1/500
2500/2500 [==============================] - 0s 135us/step - loss: 1.1984
Epoch 2/500
2500/2500 [==============================] - 0s 76us/step - loss: 1.1743
Epoch 3/500
2500/2500 [==============================] - 0s 76us/step - loss: 1.1702
Epoch 4/500
2500/2500 [==============================] - 0s 78us/step - loss: 1.1649
Epoch 5/500
2500/2500 [==============================] - 0s 90us/step - loss: 1.1575
Epoch 6/500
2500/2500 [==============================] - 0s 80us/step - loss: 1.1436
Epoch 7/500
2500/2500 [==============================] - 0s 81us/step - loss: 1.1279: 0s - loss: 1.13
Epoch 8/500
2500/2500 [==============================] - 0s 81us/step - loss: 1.1156
Epoch 9/500
2500/2500 [==============================] - 0s 82us/step - loss: 1.1063
Epoch 10/500
2500/2500 [====

2500/2500 [==============================] - 0s 90us/step - loss: 1.0760
Epoch 92/500
2500/2500 [==============================] - 0s 79us/step - loss: 1.0761
Epoch 93/500
2500/2500 [==============================] - 0s 76us/step - loss: 1.0760
Epoch 94/500
2500/2500 [==============================] - 0s 80us/step - loss: 1.0759
Epoch 95/500
2500/2500 [==============================] - 0s 77us/step - loss: 1.0760
Epoch 96/500
2500/2500 [==============================] - 0s 85us/step - loss: 1.0759
Epoch 97/500
2500/2500 [==============================] - 0s 83us/step - loss: 1.0757
Epoch 98/500
2500/2500 [==============================] - 0s 81us/step - loss: 1.0757
Epoch 99/500
2500/2500 [==============================] - 0s 86us/step - loss: 1.0757
Epoch 100/500
2500/2500 [==============================] - 0s 90us/step - loss: 1.0756
Epoch 101/500
2500/2500 [==============================] - 0s 81us/step - loss: 1.0755
Epoch 102/500
2500/2500 [==============================] - 0s 85u

2500/2500 [==============================] - 0s 91us/step - loss: 1.0724
Epoch 186/500
2500/2500 [==============================] - 0s 78us/step - loss: 1.0724
Epoch 187/500
2500/2500 [==============================] - 0s 79us/step - loss: 1.0724
Epoch 188/500
2500/2500 [==============================] - 0s 81us/step - loss: 1.0723
Epoch 189/500
2500/2500 [==============================] - 0s 82us/step - loss: 1.0723
Epoch 190/500
2500/2500 [==============================] - 0s 78us/step - loss: 1.0721
Epoch 191/500
2500/2500 [==============================] - 0s 78us/step - loss: 1.0723
Epoch 192/500
2500/2500 [==============================] - 0s 78us/step - loss: 1.0722
Epoch 193/500
2500/2500 [==============================] - 0s 75us/step - loss: 1.0723
Epoch 194/500
2500/2500 [==============================] - 0s 74us/step - loss: 1.0723
Epoch 195/500
2500/2500 [==============================] - 0s 79us/step - loss: 1.0722
Epoch 196/500
2500/2500 [==============================] 

2500/2500 [==============================] - 0s 96us/step - loss: 1.0705
Epoch 280/500
2500/2500 [==============================] - 0s 82us/step - loss: 1.0705
Epoch 281/500
2500/2500 [==============================] - 0s 121us/step - loss: 1.0704
Epoch 282/500
2500/2500 [==============================] - 0s 123us/step - loss: 1.0704
Epoch 283/500
2500/2500 [==============================] - 0s 100us/step - loss: 1.0704
Epoch 284/500
2500/2500 [==============================] - 0s 101us/step - loss: 1.0705
Epoch 285/500
2500/2500 [==============================] - 0s 93us/step - loss: 1.0704
Epoch 286/500
2500/2500 [==============================] - 0s 99us/step - loss: 1.0702
Epoch 287/500
2500/2500 [==============================] - 0s 97us/step - loss: 1.0704
Epoch 288/500
2500/2500 [==============================] - 0s 110us/step - loss: 1.0703
Epoch 289/500
2500/2500 [==============================] - 0s 104us/step - loss: 1.0704
Epoch 290/500
2500/2500 [==========================

2500/2500 [==============================] - 0s 96us/step - loss: 1.0690
Epoch 373/500
2500/2500 [==============================] - 0s 75us/step - loss: 1.0691
Epoch 374/500
2500/2500 [==============================] - 0s 118us/step - loss: 1.0690
Epoch 375/500
2500/2500 [==============================] - 0s 84us/step - loss: 1.0692
Epoch 376/500
2500/2500 [==============================] - 0s 89us/step - loss: 1.0690
Epoch 377/500
2500/2500 [==============================] - 0s 97us/step - loss: 1.0691
Epoch 378/500
2500/2500 [==============================] - 0s 140us/step - loss: 1.0691
Epoch 379/500
2500/2500 [==============================] - 0s 93us/step - loss: 1.0689
Epoch 380/500
2500/2500 [==============================] - 0s 95us/step - loss: 1.0691
Epoch 381/500
2500/2500 [==============================] - 0s 98us/step - loss: 1.0691
Epoch 382/500
2500/2500 [==============================] - 0s 105us/step - loss: 1.0690
Epoch 383/500
2500/2500 [=============================

2500/2500 [==============================] - 0s 198us/step - loss: 1.0681
Epoch 466/500
2500/2500 [==============================] - 0s 191us/step - loss: 1.0680
Epoch 467/500
2500/2500 [==============================] - 0s 162us/step - loss: 1.0682
Epoch 468/500
2500/2500 [==============================] - 0s 141us/step - loss: 1.0683
Epoch 469/500
2500/2500 [==============================] - 1s 206us/step - loss: 1.0680
Epoch 470/500
2500/2500 [==============================] - 0s 190us/step - loss: 1.0679
Epoch 471/500
2500/2500 [==============================] - 0s 173us/step - loss: 1.0680
Epoch 472/500
2500/2500 [==============================] - 1s 227us/step - loss: 1.0681
Epoch 473/500
2500/2500 [==============================] - 0s 165us/step - loss: 1.0681
Epoch 474/500
2500/2500 [==============================] - 0s 191us/step - loss: 1.0680
Epoch 475/500
2500/2500 [==============================] - 0s 147us/step - loss: 1.0679
Epoch 476/500
2500/2500 [=====================

[0 2 0 0 0 0 1 1 1 0 4 9]
[0.05517547 0.0624342  0.08460417 0.12192219 0.24060278 0.07759534
 0.05180917 0.08314697 0.0502656  0.04812098 0.12432313] [0.         0.30612245 0.         0.         0.         0.
 0.         0.         0.         0.         0.69387755]
[ 2  0  1  0  0  2  1  1  0  1  4 18]
[0.06024507 0.05740536 0.07130554 0.10341283 0.28191146 0.07765006
 0.0598998  0.06992639 0.05302661 0.04318805 0.12202878] [0.         0.         0.28571429 0.         0.         0.3877551
 0.         0.         0.         0.         0.32653061]
[ 1  0  0  1  1  1  1  1  0  1 10 21]
[0.05452566 0.03576163 0.04161903 0.11315729 0.47349298 0.06757926
 0.03289345 0.04342278 0.03718917 0.02478743 0.07557124] [0.         0.         0.         0.30666667 0.52       0.
 0.         0.         0.         0.         0.17333333]
[ 2  0  0  0  0  2  0  2  0  0 10 22]
[0.06464518 0.04066568 0.043807   0.10454684 0.4297215  0.07359298
 0.04321661 0.04531348 0.04601892 0.02903728 0.07943448] [0.      

 0.03811668 0.05510109 0.06762951 0.03755925 0.05601195] [0.         0.         0.         0.         0.         0.2987013
 0.         0.24675325 0.25974026 0.         0.19480519]
[ 0  0  0  1  0  2  1  0  0  1  2 26]
[0.05096595 0.05650872 0.07451339 0.0828822  0.27696964 0.06976481
 0.07257373 0.06909838 0.05201278 0.03888764 0.15582286] [0.         0.         0.         0.25       0.         0.11764706
 0.         0.         0.         0.         0.63235294]
[ 1  0  1  0  1  1  0  0  0  1 10 25]
[0.05266628 0.03234917 0.03690839 0.09949885 0.51062053 0.06400932
 0.03352946 0.03833168 0.03526978 0.02194741 0.07486908] [0.         0.         0.06329114 0.         0.74683544 0.
 0.         0.         0.         0.         0.18987342]
[0 0 0 0 0 0 1 3 1 1 2 4]
[0.0681024  0.08134649 0.09872299 0.12027331 0.13839605 0.08470941
 0.0645099  0.0970606  0.06954899 0.06944784 0.10788205] [0.         0.         0.         0.         0.         0.
 0.         0.40449438 0.         0.         0.

[ 2  1  0  1  0  1  1  1  0  2 10 24]
[0.05281662 0.03765802 0.04528719 0.10250942 0.45544228 0.06723837
 0.03868612 0.04614633 0.03813384 0.02599091 0.09009095] [0.         0.0955414  0.         0.27388535 0.         0.
 0.         0.         0.         0.10828025 0.52229299]
[ 0  1  0  0  0  2  0  0  1  0  3 20]
[0.06542896 0.05662437 0.06823143 0.09124468 0.2814143  0.07940499
 0.06659923 0.06638166 0.0528522  0.04632662 0.12549156] [0.       0.1875   0.       0.       0.       0.234375 0.       0.
 0.       0.       0.578125]
[ 0  1  4  0  0  0  2  0  2  1 10  9]
[0.05226881 0.03937035 0.06174041 0.27139056 0.30497786 0.04378529
 0.01905955 0.02592693 0.10629638 0.0271082  0.04807558] [0.         0.04411765 0.13235294 0.         0.         0.
 0.07352941 0.         0.54411765 0.         0.20588235]
[0 0 1 0 0 1 1 1 2 1 3 9]
[0.05575227 0.05973979 0.07898019 0.13557217 0.2650336  0.07738478
 0.04547189 0.07832211 0.05038433 0.04394768 0.10941121] [0.         0.         0.23529412 0.

[ 1  0  4  1  0  1  1  0  2  0 10 15]
[0.04121385 0.02872021 0.03262348 0.1901928  0.5174147  0.05208792
 0.01498209 0.03210283 0.03923992 0.01351551 0.03790662] [0.         0.         0.12195122 0.67073171 0.         0.
 0.         0.         0.09756098 0.         0.1097561 ]
[ 0  0  0  0  0  1  0  0  0  1 10  6]
[0.08123425 0.06455582 0.09458502 0.14862703 0.17393777 0.06788984
 0.04975788 0.05022411 0.09742179 0.07663753 0.09512892] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[ 1  2  1  0  0  2  0  1  0  3  3 12]
[0.04828452 0.06697599 0.09774023 0.10167    0.19798362 0.07247375
 0.06308451 0.09187955 0.05020328 0.05105075 0.15865386] [0.         0.13559322 0.22033898 0.         0.         0.22033898
 0.         0.         0.         0.11864407 0.30508475]
[ 1  0  0  1  1  0  0  1  0  0 -1 31]
[0.05175502 0.05338373 0.06734126 0.08063068 0.30828968 0.06835207
 0.07297789 0.06207743 0.05378615 0.03458572 0.14682035] [0.         0.         0.         0.12244898 0.59183673 0.
 0.         0.    

[0.05388268 0.03416671 0.03877282 0.10074915 0.49775174 0.06372286
 0.03525875 0.03843014 0.03833746 0.02264723 0.07628046] [0.         0.         0.19298246 0.         0.         0.
 0.         0.         0.         0.         0.80701754]
[ 1  0  1  0  0  1  1  0  1  4 10  8]
[0.0741006  0.05935708 0.06896959 0.16442826 0.26142344 0.07762317
 0.04196765 0.05806183 0.07538043 0.04541755 0.07327041] [0.         0.         0.35714286 0.         0.         0.
 0.         0.         0.         0.30952381 0.33333333]
[0 0 0 0 0 1 2 1 1 2 2 2]
[0.06263997 0.0811948  0.10365432 0.099272   0.1292344  0.08095127
 0.07527947 0.09974483 0.06546125 0.07118997 0.13137773] [0.         0.         0.         0.         0.         0.
 0.44329897 0.         0.         0.24742268 0.30927835]
[ 0  2  1  0  0  0  1  0  3  3 10  5]
[0.06719619 0.05988364 0.1019202  0.2012921  0.17207178 0.05085353
 0.03618756 0.03679511 0.13111056 0.06153091 0.08115838] [0.         0.09615385 0.17307692 0.         0.       

[ 1  0  0  0  0  2  1  0  1  0 10 17]
[0.05479478 0.03649878 0.04327983 0.11048202 0.46342522 0.06872718
 0.03424518 0.04527712 0.03646433 0.02627897 0.08052662] [0.   0.   0.   0.   0.   0.26 0.   0.   0.   0.   0.74]
[ 3  0  2  1  0  1  3  1  0  0 10 10]
[0.06749116 0.05551198 0.05942752 0.1672328  0.30959296 0.07867684
 0.03746582 0.0599336  0.06441025 0.03479042 0.06546671] [0.         0.         0.12941176 0.48235294 0.         0.
 0.10588235 0.         0.         0.         0.28235294]
[ 1  2  0  0  0  2  0  1  0  4  5 14]
[0.0550379  0.05983097 0.08117239 0.10441263 0.2517249  0.07674889
 0.05822667 0.07951547 0.04808823 0.04757419 0.13766778] [0.         0.13559322 0.         0.         0.         0.25423729
 0.         0.         0.         0.13559322 0.47457627]
[ 1  1  0  0  0  1  2  3  0  0 10  2]
[0.06322987 0.07908572 0.13926594 0.12897831 0.09595455 0.05356472
 0.0562038  0.05564949 0.10941988 0.09610628 0.12254144] [0.     0.275  0.     0.     0.     0.     0.0875 0.162

[0.05733676 0.04980611 0.06083659 0.08440925 0.3405425  0.07129539
 0.06433631 0.0571291  0.04976719 0.03567002 0.12887077] [0.         0.         0.76271186 0.         0.         0.
 0.         0.         0.         0.         0.23728814]
[ 1  0  0  1  0  0  2  1  0  1 10 27]
[0.05081457 0.03156176 0.03640611 0.09880386 0.51922977 0.06255729
 0.03262783 0.03769001 0.03426347 0.02108273 0.0749626 ] [0.         0.         0.         0.50877193 0.         0.
 0.19298246 0.         0.         0.         0.29824561]
[ 1  0  0  0  0  1  1  1  2  1 10 14]
[0.05548862 0.03793401 0.04319557 0.14460245 0.44974452 0.06855594
 0.02744608 0.04520217 0.04098712 0.02450045 0.06234311] [0.         0.         0.         0.         0.         0.
 0.         0.         0.67320261 0.         0.32679739]
[ 1  1  1  0  1  0  1  3  0  3 10  2]
[0.06997954 0.0759872  0.12635756 0.10701175 0.0905178  0.06258596
 0.06802027 0.06353321 0.09695278 0.10812651 0.13092741] [0.         0.13432836 0.37313433 0.      

[0.05157005 0.08124803 0.11507494 0.10851472 0.12709612 0.07475557
 0.06600027 0.10786621 0.05990019 0.06555718 0.14241673] [0.    0.    0.175 0.    0.    0.    0.1   0.    0.    0.075 0.65 ]
[ 1  1  0  0  0  0  0  1  2  2  2 10]
[0.05400296 0.07146046 0.09716272 0.11540066 0.18693669 0.07618346
 0.06101091 0.09214215 0.05812269 0.05338141 0.13419591] [0.         0.12820513 0.         0.         0.         0.
 0.         0.         0.14102564 0.14102564 0.58974359]
[ 1  0  0  0  0  2  0  2  0  0 10 28]
[0.06027927 0.03350156 0.03532642 0.09070804 0.49940562 0.06731229
 0.03977034 0.03678213 0.03989013 0.02339163 0.07363258] [0.         0.         0.         0.         0.         0.21428571
 0.         0.2244898  0.         0.         0.56122449]
[ 3  0  0  1  0  1  0  0  2  1 10 14]
[0.05705043 0.04440975 0.05147367 0.14478356 0.39675558 0.07156291
 0.03324658 0.05240525 0.04733481 0.02828789 0.07268955] [0.         0.         0.         0.59550562 0.         0.
 0.         0.         

 0.06942648 0.06465246 0.0483168  0.03428003 0.15943442] [0.         0.2244898  0.         0.36734694 0.         0.
 0.         0.         0.         0.         0.40816327]
[ 1  0  0  0  0  2  1  0  0  0 10 21]
[0.05694202 0.0356387  0.04136403 0.09549471 0.47012195 0.0691919
 0.03898706 0.04332261 0.03622315 0.02678408 0.08592978] [0.         0.         0.         0.         0.         0.34210526
 0.         0.         0.         0.         0.65789474]
[ 1  2  0  1  0  1  0  1  0  3 10 20]
[0.05645997 0.04187984 0.0488171  0.12621298 0.4198388  0.07056196
 0.03583119 0.04979921 0.04411132 0.02767692 0.07881073] [0.         0.23717949 0.         0.24358974 0.         0.
 0.         0.         0.         0.11538462 0.40384615]
[ 1  1  0  1  0  0  1  1  1  1 10 24]
[0.050965   0.03432578 0.04042976 0.10929853 0.49100763 0.06428897
 0.03248087 0.04157449 0.03630919 0.02257357 0.0767462 ] [0.         0.24752475 0.         0.41584158 0.         0.
 0.         0.         0.         0.       

 0.04119474 0.06436893 0.04878227 0.04001279 0.08764963] [0.         0.18461538 0.         0.         0.         0.23076923
 0.         0.         0.15384615 0.         0.43076923]
[ 1  1  0  0  1  0  1  1  0  1 10 30]
[0.04645508 0.02823073 0.03324537 0.08610309 0.55385965 0.05821607
 0.03233752 0.03424769 0.03036099 0.01875333 0.07819041] [0.         0.04587156 0.         0.         0.78899083 0.
 0.         0.         0.         0.         0.16513761]
[ 0  0  0  1  0  0  0  0  1  1 10 28]
[0.05330623 0.03098622 0.03424941 0.09894373 0.5281451  0.06238034
 0.03209912 0.03511233 0.03568619 0.0205471  0.06854421] [0.         0.         0.         0.44871795 0.         0.
 0.         0.         0.         0.         0.55128205]
[ 2  0  0  1  0  1  0  2  0  0  3 18]
[0.0736722  0.06594437 0.07399663 0.10327914 0.22765148 0.08459356
 0.06977264 0.07256994 0.06629386 0.05289165 0.1093346 ] [0.         0.         0.         0.30909091 0.         0.
 0.         0.38181818 0.         0.      

[0.06327098 0.05383405 0.06173045 0.16239557 0.3167782  0.07817236
 0.03619287 0.06286933 0.05585416 0.0359291  0.07297293] [0.         0.         0.         0.         0.58823529 0.
 0.         0.         0.11764706 0.09803922 0.19607843]
[ 2  0  0  0  0  0  1  1  4  4 10 10]
[0.07348597 0.05438646 0.05179153 0.19074565 0.3213338  0.07345632
 0.03212883 0.04745092 0.07890702 0.02985441 0.04645913] [0.         0.         0.         0.         0.         0.
 0.         0.         0.48529412 0.16176471 0.35294118]
[ 1  1  0  0  1  1  0  0  0  0 10 18]
[0.05861042 0.04041018 0.04705169 0.11220483 0.42809093 0.07206765
 0.03852411 0.04878655 0.04113025 0.02919232 0.08393113] [0.         0.06741573 0.         0.         0.80898876 0.
 0.         0.         0.         0.         0.12359551]
[ 1  0  0  1  0  1  1  0  0  1 10 28]
[0.05531095 0.03267527 0.03645389 0.09148062 0.5063126  0.06528511
 0.03737506 0.03786574 0.03631864 0.02284289 0.07807924] [0.         0.         0.         0.324324

 0.         0.         0.         0.16326531 0.65306122]
[ 3  0  3  0  0  0  0  1  1  1 10 13]
[0.06287947 0.04994266 0.05204332 0.18058617 0.3517291  0.07294282
 0.03134891 0.05205296 0.06361262 0.02756924 0.05529267] [0.   0.   0.41 0.   0.   0.   0.   0.   0.   0.   0.59]
[ 0  1  1  0  0  0  3  0  3  2  2 12]
[0.0311224  0.05241656 0.09217294 0.12197044 0.28800642 0.0583476
 0.03953537 0.08372828 0.03544707 0.03136854 0.16588433] [0.         0.12162162 0.10810811 0.         0.         0.
 0.09459459 0.         0.13513514 0.09459459 0.44594595]
[ 1  0  0  1  1  0  1  0  0  1 10 30]
[0.04915542 0.0285999  0.03244126 0.09090404 0.5517161  0.05956538
 0.03149005 0.03367244 0.03209462 0.01888658 0.07147419] [0.         0.         0.         0.08823529 0.77941176 0.
 0.         0.         0.         0.         0.13235294]
[ 1  0  0  0  0  0  1  3  1  1 10 24]
[0.05023004 0.03257394 0.03748987 0.11228169 0.51068175 0.06241795
 0.02981466 0.03863119 0.03605257 0.02059201 0.06923432] [0.    

[2 2 0 0 1 0 0 2 0 1 2 5]
[0.06463394 0.08462242 0.10624446 0.09912422 0.1141536  0.08178174
 0.07636814 0.10252753 0.06811829 0.07662321 0.12580247] [0.         0.22619048 0.         0.         0.1547619  0.
 0.         0.27380952 0.         0.         0.3452381 ]
[3 2 0 0 0 2 3 0 1 3 4 4]
[0.05418319 0.0751386  0.10515337 0.0988532  0.15011165 0.07686295
 0.06943554 0.10035796 0.05542281 0.06402938 0.15045136] [0.         0.14285714 0.         0.         0.         0.14285714
 0.26530612 0.         0.         0.12244898 0.32653061]
[ 1  1  1  0  0  0  0  0  2  0  3 19]
[0.05695182 0.05310192 0.06669102 0.1096394  0.31918094 0.07464629
 0.05231263 0.06514709 0.04972348 0.03791537 0.11469002] [0.         0.16363636 0.2        0.         0.         0.
 0.         0.         0.23636364 0.         0.4       ]
[3 0 0 0 0 2 2 1 1 0 3 7]
[0.05724366 0.06729986 0.08974827 0.11758514 0.2098386  0.07888085
 0.05737406 0.08748863 0.05465596 0.05285077 0.12703417] [0.         0.         0.       

 0.06382121 0.07042573 0.05187713 0.04252339 0.13385966] [0.         0.16363636 0.         0.         0.         0.
 0.         0.23636364 0.         0.         0.6       ]
[0 2 1 0 0 0 1 1 0 4 4 4]
[0.06008039 0.07565271 0.1062664  0.12358527 0.13740188 0.07653964
 0.06378777 0.09095428 0.07402424 0.06730541 0.12440201] [0.         0.2244898  0.30612245 0.         0.         0.
 0.         0.         0.         0.26530612 0.20408163]
[ 1  1  0  0  0  1  1  0  0  1 -1 31]
[0.04331256 0.05093716 0.07251902 0.0790805  0.30891126 0.06417247
 0.06631434 0.06650601 0.04393726 0.03373891 0.1705705 ] [0.         0.36734694 0.         0.         0.         0.
 0.         0.         0.         0.         0.63265306]
[ 1  0  1  0  0  0  0  0  2  2 10 27]
[0.04686287 0.02893943 0.0332865  0.10196756 0.5501953  0.0582803
 0.02830726 0.03427994 0.03266244 0.01793497 0.06728352] [0.         0.         0.25454545 0.         0.         0.
 0.         0.         0.08181818 0.12727273 0.53636364]
[ 1  0

[ 2  0  2  0  0  1  1  0  1  1 10 18]
[0.04547457 0.03332131 0.04083165 0.12903617 0.49910516 0.06071601
 0.02587417 0.04174915 0.03457052 0.02012643 0.06919486] [0.         0.         0.41052632 0.         0.         0.
 0.         0.         0.         0.         0.58947368]
[0 1 0 0 0 0 3 0 1 2 4 1]
[0.06378733 0.09305333 0.11691671 0.1267358  0.12124337 0.06943723
 0.06277239 0.08308365 0.08840698 0.06895509 0.10560814] [0.         0.03703704 0.         0.         0.         0.
 0.14814815 0.         0.         0.09876543 0.71604938]
[ 1  0  1  0  0  1  1  1  1  0 10 25]
[0.04939955 0.02966265 0.03369413 0.10208535 0.54075724 0.06036968
 0.02923731 0.0350181  0.03329833 0.01910705 0.06737068] [0.         0.         0.61271676 0.         0.         0.
 0.         0.         0.         0.         0.38728324]
[ 1  1  0  0  0  1  3  1  1  0 10 19]
[0.04091734 0.02916106 0.03884671 0.10217082 0.5335343  0.0579378
 0.02667491 0.04034717 0.02619022 0.01997344 0.0842462 ] [0.        0.1484

 0.03008095 0.04036589 0.029912   0.02134184 0.08229185] [0.         0.15584416 0.         0.         0.         0.
 0.14285714 0.         0.         0.         0.7012987 ]
[ 1  1  0  0  0  1  1  2  1  2 10 14]
[0.06102666 0.04341168 0.04834579 0.14955726 0.40131745 0.07347994
 0.03144252 0.05027915 0.0474805  0.02861431 0.06504473] [0.         0.16363636 0.         0.         0.         0.
 0.         0.32727273 0.         0.14545455 0.36363636]
[2 3 2 1 0 1 4 0 0 1 2 5]
[0.04404611 0.0754967  0.11403473 0.11460709 0.15605119 0.06931034
 0.05998038 0.10388052 0.05559629 0.05304457 0.1539522 ] [0.         0.14285714 0.16666667 0.29761905 0.         0.
 0.11904762 0.         0.         0.         0.27380952]
[ 1  1  1  0  0  1  2  0  1  2 10  6]
[0.07096191 0.0633992  0.0856981  0.18011326 0.21975486 0.06886086
 0.03855978 0.05489571 0.08300368 0.05504699 0.07970573] [0.         0.13888889 0.53703704 0.         0.         0.
 0.09259259 0.         0.         0.09259259 0.13888889]
[ 2  

[ 1  1  0  0  0  0  1  0  2  0  4 29]
[0.05178097 0.03815452 0.0468778  0.08260667 0.44287086 0.06620103
 0.04870571 0.04657997 0.03786921 0.02718206 0.11117127] [0.         0.20408163 0.         0.         0.         0.
 0.         0.         0.14285714 0.         0.65306122]
[ 3  1  2  0  0  0  2  1  2  1 10  9]
[0.06969438 0.06243722 0.06436822 0.19036591 0.27882785 0.07122592
 0.03549479 0.05321601 0.08401245 0.03441097 0.05594629] [0.         0.12658228 0.25316456 0.         0.         0.
 0.08860759 0.         0.21518987 0.         0.3164557 ]
[ 1  0  0  0  0  2  1  0  2  0  4 24]
[0.05979788 0.04631385 0.05541489 0.09196717 0.37221116 0.07307404
 0.05461125 0.05409275 0.0459968  0.03461159 0.11190865] [0.         0.         0.         0.         0.         0.2244898
 0.         0.         0.14285714 0.         0.63265306]
[ 2  0  0  0  0  1  2  3  2  0  5 11]
[0.06043106 0.05681863 0.06969868 0.1371888  0.29354423 0.07840423
 0.04456143 0.06978146 0.05336205 0.04050763 0.0957018

 0.         0.         0.         0.         0.17333333]
[ 1  1  1  0  0  1  2  1  2  1 10 12]
[0.05296215 0.03902836 0.04390707 0.1724102  0.43579838 0.06612186
 0.02371458 0.04519885 0.04479819 0.0223111  0.05374921] [0.         0.27631579 0.13157895 0.         0.         0.
 0.19736842 0.         0.18421053 0.         0.21052632]
[ 1  0  0  1  0  1  0  0  1  1 -1 31]
[0.05073417 0.05315538 0.06801195 0.08051334 0.30817416 0.06790971
 0.07221811 0.06266265 0.05257095 0.03454544 0.14950408] [0.         0.         0.         0.42857143 0.         0.
 0.         0.         0.         0.         0.57142857]
[ 1  0  0  1  1  0  2  0  0  0 -1 31]
[0.04363465 0.05004057 0.07010339 0.07838016 0.31944802 0.06379437
 0.06650734 0.06417494 0.04453833 0.03250337 0.16687487] [0.         0.         0.         0.06122449 0.63265306 0.
 0.06122449 0.         0.         0.         0.24489796]
[ 1  0  2  0  0  1  2  1  2  1  4 12]
[0.04583003 0.04975258 0.06941968 0.14115955 0.34160343 0.0684909
 0.03

[ 2  0  1  1  0  1  0  1  0  1 10 20]
[0.06076122 0.04250148 0.04728933 0.12491254 0.41579324 0.07246453
 0.0374999  0.04847297 0.04717075 0.0283071  0.07482699] [0.         0.         0.15104167 0.44791667 0.         0.
 0.         0.         0.         0.         0.40104167]
[ 1  2  0  0  0  1  1  0  0  0 10 19]
[0.05152713 0.03763849 0.04729667 0.10207018 0.448257   0.06793424
 0.0378377  0.04871134 0.03503519 0.02758669 0.09610538] [0.         0.10714286 0.         0.         0.         0.
 0.         0.         0.         0.         0.89285714]
[2 2 0 1 0 2 1 3 3 0 4 7]
[0.0587071  0.07225172 0.09183177 0.14398654 0.19506295 0.07884928
 0.05119493 0.08850545 0.06444412 0.05083306 0.10433304] [0.         0.18367347 0.         0.26530612 0.         0.10204082
 0.         0.14285714 0.10204082 0.         0.20408163]
[1 0 0 0 0 1 1 2 2 2 2 8]
[0.05519721 0.07139844 0.09680884 0.12002873 0.18664902 0.077545
 0.05829948 0.09292288 0.05725244 0.0547173  0.12918067] [0.         0.        

[0.04861023 0.03748192 0.04473945 0.14748073 0.4583328  0.06373962
 0.02635449 0.04540276 0.04037239 0.02183393 0.06565171] [0.         0.13978495 0.32258065 0.         0.         0.
 0.         0.19354839 0.         0.         0.34408602]
[ 1  2  0  0  0  1  2  0  2  0 10  2]
[0.05405924 0.08252647 0.14612076 0.16741529 0.11163939 0.04273736
 0.04342547 0.04460108 0.13581532 0.06936826 0.10229138] [0.         0.23863636 0.         0.         0.         0.
 0.19318182 0.         0.36363636 0.         0.20454545]
[ 2  1  1  0  0  1  0  1  0  1  4 23]
[0.06149145 0.05283358 0.06365395 0.09348291 0.3151543  0.0765726
 0.06200242 0.06260611 0.05116645 0.03990951 0.12112668] [0.         0.18367347 0.24489796 0.         0.         0.
 0.         0.         0.         0.         0.57142857]
[ 1  1  1  0  0  0  1  4  2  0 10  1]
[0.07223511 0.07502363 0.13168167 0.11171552 0.08408108 0.05405428
 0.06496055 0.04927758 0.1220144  0.11264919 0.12230703] [0.         0.11940299 0.20895522 0.       

 0.05806372 0.05613588 0.03918953 0.02957428 0.148304  ] [0.         0.08163265 0.         0.         0.         0.
 0.10204082 0.         0.         0.         0.81632653]
[ 1  1  1  1  0  0  1  0  0  1  2 26]
[0.04826669 0.05327473 0.07310327 0.08604199 0.29800978 0.06870468
 0.06457598 0.0686461  0.04623562 0.03730408 0.15583712] [0.         0.18055556 0.20833333 0.13888889 0.         0.
 0.         0.         0.         0.         0.47222222]
[ 1  0  0  0  0  1  3  2  2  1 10 14]
[0.05153381 0.03458123 0.03986932 0.14353742 0.48114124 0.06480023
 0.02450904 0.04180656 0.03739611 0.0216938  0.05913125] [0.         0.         0.         0.         0.         0.
 0.17171717 0.2020202  0.11111111 0.         0.51515152]
[ 0  2  1  0  0  1  0  1  0  0  3 13]
[0.06093876 0.06525467 0.08335049 0.10839347 0.22364083 0.08015507
 0.06218805 0.08161795 0.05595599 0.05193683 0.12656789] [0.         0.15254237 0.30508475 0.         0.         0.
 0.         0.         0.         0.         0.542

[1 0 0 1 0 1 2 3 0 2 2 5]
[0.06429153 0.08235332 0.10435086 0.09927221 0.12246154 0.08212768
 0.07514834 0.10127103 0.06558321 0.07484242 0.12829785] [0.         0.         0.         0.21621622 0.         0.
 0.2027027  0.22972973 0.         0.10810811 0.24324324]
[ 1  0  0  0  0  4  2  1  0  1 10 20]
[0.05014569 0.03195636 0.03943293 0.09176254 0.5030668  0.06466014
 0.03445819 0.04149541 0.03015768 0.02421198 0.08865234] [0.        0.        0.        0.        0.        0.2109375 0.1640625
 0.        0.        0.        0.625    ]
[ 2  1  0  0  0  3  0  2  1  3 10 12]
[0.07501224 0.05511619 0.05769858 0.14571515 0.30854523 0.08368024
 0.04283652 0.05968184 0.06202057 0.03949885 0.07019453] [0.         0.11904762 0.         0.         0.         0.22619048
 0.         0.13095238 0.         0.16666667 0.35714286]
[ 1  1  0  0  0  0  0  0  1  1  8 23]
[0.05798838 0.04190774 0.04945254 0.09981763 0.41366777 0.07179289
 0.04544181 0.05028722 0.04241666 0.0303432  0.09688409] [0.        

 0.0409579  0.0481206  0.04402428 0.02769717 0.08618281] [0.         0.17857143 0.         0.         0.         0.
 0.         0.28571429 0.         0.         0.53571429]
[ 1  0  0  1  0  0  0  1  0  1 10 24]
[0.06066238 0.03939942 0.04335988 0.11080803 0.4433243  0.07108979
 0.03894225 0.0446944  0.04419509 0.02697668 0.07654779] [0.         0.         0.         0.57142857 0.         0.
 0.         0.         0.         0.         0.42857143]
[ 1  0  0  0  0  1  2  0  0  1  4 27]
[0.05063188 0.04531083 0.05904802 0.08124626 0.36669505 0.0683487
 0.05900514 0.05720505 0.04157018 0.0326787  0.13826023] [0.         0.         0.         0.         0.         0.
 0.20408163 0.         0.         0.         0.79591837]
[1 2 1 0 0 0 0 3 0 0 4 6]
[0.0712528  0.08457831 0.09937665 0.12408883 0.13645491 0.08198628
 0.06456102 0.08970471 0.07841245 0.06919264 0.10039138] [0.         0.2244898  0.30612245 0.         0.         0.
 0.         0.2244898  0.         0.         0.24489796]
[ 2  0

[0.04395482 0.03446092 0.04483592 0.11143097 0.4848416  0.06126162
 0.03083979 0.04534197 0.03266829 0.02219321 0.0881709 ] [0.         0.05109489 0.06569343 0.         0.         0.
 0.         0.         0.         0.         0.88321168]
[ 1  0  0  1  0  1  0  1  2  1  4 17]
[0.06593456 0.05725549 0.06662207 0.12051036 0.29210263 0.08051249
 0.05259228 0.06664717 0.05708503 0.04207834 0.09865961] [0.         0.         0.         0.36734694 0.         0.
 0.         0.         0.2244898  0.         0.40816327]
[ 1  0  0  0  0  2  0  1  0  2  3 27]
[0.05378499 0.05492102 0.06904886 0.08255736 0.29559976 0.0704717
 0.07293672 0.06433637 0.05416119 0.03710386 0.14507824] [0.         0.         0.         0.         0.         0.12280702
 0.         0.         0.         0.10526316 0.77192982]
[ 1  2  0  1  0  0  2  1  0  2 10  1]
[0.06088079 0.07557034 0.14433572 0.12211528 0.09059463 0.05115499
 0.05911637 0.05617449 0.10819998 0.10174229 0.13011514] [0.         0.11940299 0.         0

[ 0  1  2  1  0  1  2  0  0  1  2 13]
[0.04284902 0.06124209 0.09318358 0.11793139 0.24144574 0.06842914
 0.05061352 0.08700633 0.04605691 0.04157574 0.14966653] [0.         0.0952381  0.19047619 0.31746032 0.         0.
 0.20634921 0.         0.         0.         0.19047619]
[ 1  1  0  1  0  1  0  0  3  2 10 11]
[0.05922687 0.04327695 0.05248802 0.19658867 0.36705932 0.06534006
 0.02595809 0.04354597 0.0624488  0.02805546 0.05601183] [0.         0.19277108 0.         0.39759036 0.         0.
 0.         0.         0.13253012 0.08433735 0.19277108]
[ 0  2  1  0  0  2  0  2  0  3  3 10]
[0.05390728 0.06824388 0.09447234 0.11376942 0.19940236 0.07693016
 0.0586817  0.09106623 0.0531163  0.05351818 0.13689214] [0.         0.16949153 0.11864407 0.         0.         0.20338983
 0.         0.18644068 0.         0.13559322 0.18644068]
[ 0  0  1  0  0  0  1  1  3  3  3 13]
[0.04503686 0.05697569 0.08219214 0.1339835  0.2840963  0.06916387
 0.04316579 0.07814795 0.0465599  0.03674931 0.123928

 0.04912319 0.06264314 0.04247597 0.03357431 0.12485447] [0.         0.2244898  0.         0.         0.         0.
 0.         0.         0.24489796 0.         0.53061224]
[ 2  2  0  0  0  0  0  1  1  1 10 23]
[0.05296495 0.03878823 0.04666396 0.10409383 0.44595188 0.06756993
 0.03956942 0.04724653 0.03951046 0.02638199 0.09125882] [0.         0.19753086 0.         0.         0.         0.
 0.         0.         0.         0.         0.80246914]
[ 1  0  0  0  0  1  3  1  0  1 10 23]
[0.04542689 0.02945835 0.03691247 0.0929653  0.5332181  0.06011795
 0.03057086 0.03851161 0.02825234 0.02083698 0.08372917] [0.         0.         0.         0.         0.         0.
 0.51685393 0.         0.         0.         0.48314607]
[ 0  2  0  1  0  1  1  0  1  1  3 19]
[0.05084236 0.05669523 0.07785828 0.09963167 0.27689648 0.07240438
 0.05874842 0.07457604 0.04730662 0.04143264 0.14360784] [0.         0.13207547 0.         0.28301887 0.         0.
 0.         0.         0.         0.         0.584

[ 1  0  1  1  0  0  0  2  0  0 10 30]
[0.05301823 0.03027208 0.03232459 0.1026944  0.5402084  0.06041101
 0.03040416 0.03267849 0.0376302  0.01870483 0.06165368] [0.         0.         0.59259259 0.14814815 0.         0.
 0.         0.11111111 0.         0.         0.14814815]
[1 2 0 0 0 2 0 0 0 1 4 2]
[0.06683406 0.08521037 0.10954361 0.1016855  0.10862108 0.0788125
 0.07544334 0.09505108 0.07447349 0.08130884 0.12301612] [0.         0.11111111 0.         0.         0.         0.12962963
 0.         0.         0.         0.         0.75925926]
[ 2  1  2  0  0  2  1  1  2  0 10 17]
[0.04048116 0.03057771 0.03937088 0.12670489 0.5241832  0.05688794
 0.02312108 0.04022191 0.03016303 0.01820176 0.07008636] [0.         0.12048193 0.21686747 0.         0.         0.26506024
 0.         0.         0.18072289 0.         0.21686747]
[ 2  2  0  0  0  1  3  1  2  1 10 12]
[0.05334233 0.04234531 0.04979704 0.15598084 0.41229865 0.06858397
 0.02886325 0.05064863 0.04522757 0.02563392 0.06727841] [